### ISSUE TITLE
Blog posts sobre Tecnologia

### ISSUE THREAD

**Issue by scarpelini** [frontendbr/survey#1]
Bom dia pessoal, gostaria de saber de vocês da comunidade Front-end BR se interessariam em escrever sobre tecnologia para o Blog de uma empresa em específico. Nós estamos buscando desenvolvedores experientes que possuem uma boa gama de conhecimento que possam compartilhar (em inglês de preferência) em nosso Blog. 

Como nossa equipe ainda é reduzida, estamos em busca de profissionais que gostam de escrever sobre tecnologia(desenvolvimento Front-end, Back-end, Chatbots, DevOps, Infra, etc) para nos ajudar com essas demandas de criação de conteúdo relevante.

O que acham? Haveria interesse? Se sim, qual tema tem knowhow para abordar?

Abraços

**Comment by LFeh** [comment]
Amigo, esse repositório serve tão somente para o Survey que estamos lançando.

Recomendo que poste no https://github.com/frontendbr/forum

**Comment by scarpelini** [comment]
Obrigado @LFeh, farei isso.

[]'s
