### ISSUE TITLE
Salário Mulheres Junior contém faixa salarial duplicada

### ISSUE THREAD

**Issue by MiattoRocha** [frontendbr/survey#10]
Olá, 
Verifiquei que o salário de mulheres junior contém uma faixa salarial duplicada, segue imagem abaixo.
Vi que o gráfico vem de um arquivo JSON mas não consegui identificar se deveria ter outra faixa que foi omitida ou se realmente não deveria existir.
![image](https://user-images.githubusercontent.com/5280302/48342224-41c7f700-e656-11e8-9cec-86ab842db514.png)

**Comment by LFeh** [comment]
My bad pela madrugada, hahaha.

Fui fazer um depara de alguns números na mão e dupliquei sem querer. 

Corrigido!
